export const error = {
    MAX_CAMS_IN_GROUP_REACHED: 'MAX_CAMS_IN_GROUP_REACHED',
    MAX_CAM_GROUPS_REACHED: 'MAX_CAM_GROUPS_REACHED',
    CAM_GROUP_NAME_EXISTS: 'CAM_GROUP_NAME_EXISTS',
    CAM_GROUP_NOT_FOUND: 'CAM_GROUP_NOT_FOUND',
    CAM_NOT_FOUND: 'CAM_NOT_FOUND',
    CAM_GROUP_EMPTY: 'CAM_GROUP_EMPTY'
};